### ISSUE TITLE
새로고침

### ISSUE THREAD

**Issue by baboseojin** [EntryHack/entry-image#2]
url과 관계없이 그냥 페이지를 새로고침하면 업로드 버튼/이미지 보기 인터페이스가 전부 사라져버리내요
제가 확장기능 압축을 풀거나 적용하는 과정에서 문제가 잇엇을거같기도 한대...하여튼 그렅내요

엄 근대 여기다 올리는거 마자요?
깃허브 사실상 한번도 제대로 써본적이 없ㅇ

**Comment by thoratica** [comment]
아 파폭이랑 크롬이 다르게 동작하네요... 미리 테스트했어야 했는데 ㅠㅠ 아무튼 감사합니다.

**Comment by thoratica** [comment]
@baboseojin  버그가 픽스된 1.0.1이 릴리즈되었습니다.
