### ISSUE TITLE
마이 페이지에서 사진이 안떠요!

### ISSUE THREAD

**Issue by 614project** [EntryHack/entry-image#6]
엔트리 => 마이 페이지  => 엔트리 이야기

가서 보니까, 제가 올린 사진들이 안보입니다, 마이 페이지에서도 보이게 해야될꺼 같은데요.

**Comment by thoratica** [comment]
인지하고 있었지만 딱히 수정할 생각은 없었어요. 시간 되면 만들어보긴 할게요.

**Comment by thoratica** [comment]
@614project 수정되었습니다.
