### ISSUE TITLE
게시글 업로드 정지시 팝업 알림 오류

### ISSUE THREAD

**Issue by baboseojin** [EntryHack/entry-image#8]
Opera GX 78.0.4093.153로 e-img 최신버전에서 글을 올리려구 했는데 안되길래 
알고보니까 429가 계속 날라오구 잇더라구요.

더 설명할게 업따.

**Comment by baboseojin** [comment]
+ 아예 팝업 알림이 뜨질 않고 그냥 실행이 안돼네영

**Comment by thoratica** [comment]
개발안하고있었는데이것도하긴해야겠네

**Comment by baboseojin** [comment]
엌ㅋㅋㅋㅋㅋ

**Comment by thoratica** [comment]
개발 종료돼서 닫음. 개발은 entry-uploader 레포에서 새로 시작합니다.
